spring:
  application:
    name: ${NOMBRE_MICROSERVICIO:ms-water-quality}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:sistemajass}:${MONGO_PASSWORD:ZC7O1Ok40SwkfEje}@sistemajass.jn6cpoz.mongodb.net/${MONGO_DATABASE:JASS_DIGITAL}?retryWrites=true&w=majority&maxPoolSize=5&minPoolSize=1&maxIdleTimeMS=30000&serverSelectionTimeoutMS=5000
  web:
    resources:
      cache:
        period: 86400

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass
          jwk-set-uri: https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass/protocol/openid-connect/certs
server:
  port: ${PORT:8087}
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  http2:
    enabled: true

# Swagger disabled by default for production
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:false}
  default-produces-media-type: application/json
  paths-to-match: /api/**

# Minimal actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never

# Minimal logging for production
logging:
  level:
    root: ERROR
    "[pe.edu.vallegrande]": WARN
    "[org.springframework]": ERROR
    "[org.mongodb]": ERROR
    "[org.springframework.web]": ERROR
    reactor: ERROR
  pattern:
    console: "%d{HH:mm:ss} %msg%n"

# Application info
info:
  app:
    name: Water Quality Microservice
    description: Microservicio para gestión de calidad de agua
    version: 1.0.0

# External Services Configuration
user-service:
  base-url: ${USER_SERVICE_URL:https://lab.vallegrande.edu.pe/jass/ms-users}
  timeout: 5000

organization-service:
  base-url: ${ORGANIZATION_SERVICE_URL:https://lab.vallegrande.edu.pe/jass/ms-organization}
  token: ${ORGANIZATION_SERVICE_TOKEN:your-super-admin-token-here}
